name: flutter_auth_ui
description: A Flutter plugin for using the Firebase Auth UI with Dart in Flutter apps.
version: 0.2.0
homepage: https://github.com/koji-1009/flutter_auth_ui

flutter:
  plugin:
    platforms:
      android:
        package: com.dr1009.app.flutter_auth_ui
        pluginClass: FlutterAuthUiPlugin
      ios:
        pluginClass: SwiftFlutterAuthUiPlugin

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.15.4
  flutter_plugin_android_lifecycle: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"
