name: flutter_auth_ui_web
description: Unofficial firebaseui package for flutter. This library aims to provide support for Android, iOS and the web. Login with Email, Phone, Google account and etc.
version: 2.0.0-dev.0
homepage: https://github.com/koji-1009/flutter_auth_ui

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterAuthUiWeb
        fileName: flutter_auth_ui_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  firebase: ^9.0.2
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"
